### ISSUE TITLE
Problem: empty MCU Type list with localized avr-gcc

### ISSUE THREAD

**Issue by jgeisler0303** [mnlipp/avr-eclipse-fork#1]
Just to let everybody know: there is a problem on Linux systems with a localized version of avr-gcc. If the system language is not English and there are translations present for the active language, the query `avr-gcc -Wa,-mlist-devices --target-help` may not contain the key phrase `Known MCU names` but the localized version of it and thus the plugin cannot find the list of supported devices. This results in the "MCU Type"-list in "project properties / AVR/Target Hardware" being empty.
A reliable workaround for this is to rename avr-gcc to avr-gcc-real and create a bash script named avr-gcc with this content:

```
#!/bin/bash

LC_MESSAGES=C avr-gcc-real $@
```

**Comment by Lahorde** [comment]
+1 on an arch machine with avr packages.  many thanks... I googled about this issue on http://sourceforge.net/p/avr-eclipse/discussion/ and did not found a correct solution (when replacing de.innot.avreclipse.core_2.4.1.jar avrdude did not found any compatible MCUs...)

Lahorde

**Comment by joanfgarcia** [comment]
You can also create a launcher for eclipse on eclipse folder:

#!/bin/bash
LC_MESSAGES=C ./eclipse

**Comment by mnlipp** [comment]
This should be fixed by merging the R2.4.2 branch from the original project.
