### ISSUE TITLE
How do you build your plugin ?

### ISSUE THREAD

**Issue by gdoffe** [mnlipp/avr-eclipse-fork#3]
Hi,

I want to build your plugin to use on Luna or Mars versions of eclipse but how can I build it ?

Maven build ('mvn clean install') does not work and you do not support it, so could you provide me a simple way to build it and install it ?

Thx,
gdo

**Comment by mnlipp** [comment]
Why would you want to use something complicated like maven? This is a standard eclipse plugin. Simply open the site.xml in de.innot.avreclipse-updatesite and click on the button "Build All".
- Michael

**Comment by gdoffe** [comment]
Hello Michael,

Thx for your quick reply...

I do not want to use Maven, and I do not care about that ! ;)
I just want to build and install that plugin...
I'm sure you have done a great job, but I cannot test it since I'm not an Eclipse developper and I do not want to become one... :)
I can do an effort, but what is easy for you is not for me. Can you just add few lines to your README.md to explain how to build your plugin please ?

> This is a standard eclipse plugin. Simply open the site.xml in de.innot.avreclipse-updatesite and click on the button "Build All".

Ok so I guess that I should import your sources under a project... But what kind of project ?
Should the root folder be considered as a workspace or as a project ?
Should I import each folder in a new dedicated project ? (feature, update-site, etc...)

Thank you for your help. :)
gdo

**Comment by gdoffe** [comment]
So here is the process (tested on eclipse Mars 4.5) :

Once eclipse is opened:
- Select the project root folder as the workspace
- Go to menu 'File->Import' and select 'General->Existing Projects into Workspace'
- Set 'Select root directory:' path to your workspace one
- Click on 'Select all'
- Click on Finish

Once done you should see all the folders from git repository as projects. Just follow previous Michael instructions to build :

> Simply open the site.xml in de.innot.avreclipse-updatesite and click on the button "Build All".

Once done, you have to install the plugin :
- Go to 'Help->Install New Software...'
- Click on 'Add'
- Click on 'Local'
- Select the de.innot.avreclipse-updatesite folder in your workspace
- Uncheck 'Group items by category'
- Select both plugins
- Click on Finish
- Click 'Ok' if a popup appears to trust the plugin
- Click 'Ok' to restart Eclipse

gdo
